Create win_mshta_invoke_html.yml
Neo23x0/sigma pull request #1222
Opened 2020-10-18 11:59 UTC by feedb

2020-10-18 23:49 UTC, w0rk3r requested changes
Hey @feedb, thanks a lot for the contribution, here are some small changes/small improvements to the rule be ready to merge

2020-10-18 23:49 UTC, w0rk3r commented on rules/windows/process_creation/process_creation_msdeploy.yml
> +title: Msdeploy.exe LOLBIN
Consider a more elaborated title, like "Execute Files with Msdeploy.exe"

2020-10-18 23:49 UTC, w0rk3r commented on rules/windows/process_creation/process_creation_msdeploy.yml
> +description: launch binary via msdeploy.exe
Consider a more elaborated description, like "Detects file execution using the msdeploy.exe lolbin"

2020-10-18 23:49 UTC, w0rk3r commented on rules/windows/process_creation/process_creation_msdeploy.yml
> +        ProcessCommandline|contains|all:
ProcessCommandline should be replaced with CommandLine to maintain the standard of the process_creation category

2020-10-18 23:49 UTC, w0rk3r commented on rules/windows/process_creation/process_creation_msdeploy.yml
> +    - ParentCommandLine
ProcessCommandline should be replaced with CommandLine to maintain the standard of the process_creation category

2020-11-04 22:16 UTC, yugoslavskiy commented
Thank you very much, @feedb! Great work, mate!

2020-11-04 22:17 UTC, yugoslavskiy approved these changes
@thomaspatzke @Neo23x0 guys, I believe that this PR could be merged (:
please let us know what do you think about it if there is anything you would like to change.

2021-01-05 21:23 UTC, merged